/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:c44245f5-32d0-4666-8a31-dc4bc043d00c",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_AooiuG2Qe",
    "aws_user_pools_web_client_id": "6nptroln1rqsrlvqrfl0cku5ee",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://6q5sbnsuund5rcgagvaqhfb5vi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-f3uioiwayjdybai76ch5kain7y",
    "aws_user_files_s3_bucket": "metalien-storage-1604200273325-staging",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
